package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: Advertiser.
 * @author autogenerated
 */

public interface IAdvertiser {



    /**
     * Return the value associated with the column: advertiserName.
	 * @return A String object (this.advertiserName)
	 */
	String getAdvertiserName();
	

  
    /**  
     * Set the value related to the column: advertiserName.
	 * @param advertiserName the advertiserName value you wish to set
	 */
	void setAdvertiserName(final String advertiserName);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

	// end of interface
}