package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: CampaignReportingType.
 * @author autogenerated
 */

public interface ICampaignreportingtype {



    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: reportingType.
	 * @return A String object (this.reportingType)
	 */
	String getReportingType();
	

  
    /**  
     * Set the value related to the column: reportingType.
	 * @param reportingType the reportingType value you wish to set
	 */
	void setReportingType(final String reportingType);

	// end of interface
}