package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: CampaignType.
 * @author autogenerated
 */

public interface ICampaigntype {



    /**
     * Return the value associated with the column: campaignType.
	 * @return A String object (this.campaignType)
	 */
	String getCampaignType();
	

  
    /**  
     * Set the value related to the column: campaignType.
	 * @param campaignType the campaignType value you wish to set
	 */
	void setCampaignType(final String campaignType);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

	// end of interface
}