package com.cm.rotator.domain.rotator.model.obj.rotator.iface;
import java.util.Date;


/** 
 * Object interface mapping for hibernate-handled table: ConvertedTraffic.
 * @author autogenerated
 */

public interface IConvertedtraffic {



    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	Date getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Date createdAt);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: rawTrafficId.
	 * @return A Long object (this.rawTrafficId)
	 */
	Long getRawTrafficId();
	

  
    /**  
     * Set the value related to the column: rawTrafficId.
	 * @param rawTrafficId the rawTrafficId value you wish to set
	 */
	void setRawTrafficId(final Long rawTrafficId);

    /**
     * Return the value associated with the column: requestDataId.
	 * @return A Long object (this.requestDataId)
	 */
	Long getRequestDataId();
	

  
    /**  
     * Set the value related to the column: requestDataId.
	 * @param requestDataId the requestDataId value you wish to set
	 */
	void setRequestDataId(final Long requestDataId);

    /**
     * Return the value associated with the column: tag.
	 * @return A String object (this.tag)
	 */
	String getTag();
	

  
    /**  
     * Set the value related to the column: tag.
	 * @param tag the tag value you wish to set
	 */
	void setTag(final String tag);

	// end of interface
}