package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: CountryUrlCampaign.
 * @author autogenerated
 */

public interface ICountryurlcampaign {



    /**
     * Return the value associated with the column: advertiserId.
	 * @return A Long object (this.advertiserId)
	 */
	Long getAdvertiserId();
	

  
    /**  
     * Set the value related to the column: advertiserId.
	 * @param advertiserId the advertiserId value you wish to set
	 */
	void setAdvertiserId(final Long advertiserId);

    /**
     * Return the value associated with the column: campaignName.
	 * @return A String object (this.campaignName)
	 */
	String getCampaignName();
	

  
    /**  
     * Set the value related to the column: campaignName.
	 * @param campaignName the campaignName value you wish to set
	 */
	void setCampaignName(final String campaignName);

    /**
     * Return the value associated with the column: campaignTypeId.
	 * @return A Byte object (this.campaignTypeId)
	 */
	Byte getCampaignTypeId();
	

  
    /**  
     * Set the value related to the column: campaignTypeId.
	 * @param campaignTypeId the campaignTypeId value you wish to set
	 */
	void setCampaignTypeId(final Byte campaignTypeId);

    /**
     * Return the value associated with the column: campaignUrl.
	 * @return A String object (this.campaignUrl)
	 */
	String getCampaignUrl();
	

  
    /**  
     * Set the value related to the column: campaignUrl.
	 * @param campaignUrl the campaignUrl value you wish to set
	 */
	void setCampaignUrl(final String campaignUrl);

    /**
     * Return the value associated with the column: campaignValue.
	 * @return A java.math.BigDecimal object (this.campaignValue)
	 */
	java.math.BigDecimal getCampaignValue();
	

  
    /**  
     * Set the value related to the column: campaignValue.
	 * @param campaignValue the campaignValue value you wish to set
	 */
	void setCampaignValue(final java.math.BigDecimal campaignValue);

    /**
     * Return the value associated with the column: countryCode.
	 * @return A String object (this.countryCode)
	 */
	String getCountryCode();
	

  
    /**  
     * Set the value related to the column: countryCode.
	 * @param countryCode the countryCode value you wish to set
	 */
	void setCountryCode(final String countryCode);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: reportingTypeId.
	 * @return A Byte object (this.reportingTypeId)
	 */
	Byte getReportingTypeId();
	

  
    /**  
     * Set the value related to the column: reportingTypeId.
	 * @param reportingTypeId the reportingTypeId value you wish to set
	 */
	void setReportingTypeId(final Byte reportingTypeId);

	// end of interface
}