package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: ForeignSet.
 * @author autogenerated
 */

public interface IForeignset {



    /**
     * Return the value associated with the column: defaultCountryUrlCampaignId.
	 * @return A Long object (this.defaultCountryUrlCampaignId)
	 */
	Long getDefaultCountryUrlCampaignId();
	

  
    /**  
     * Set the value related to the column: defaultCountryUrlCampaignId.
	 * @param defaultCountryUrlCampaignId the defaultCountryUrlCampaignId value you wish to set
	 */
	void setDefaultCountryUrlCampaignId(final Long defaultCountryUrlCampaignId);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: setName.
	 * @return A String object (this.setName)
	 */
	String getSetName();
	

  
    /**  
     * Set the value related to the column: setName.
	 * @param setName the setName value you wish to set
	 */
	void setSetName(final String setName);

	// end of interface
}