package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: ProxyServer.
 * @author autogenerated
 */

public interface IProxyserver {



    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: proxyServerIp.
	 * @return A String object (this.proxyServerIp)
	 */
	String getProxyServerIp();
	

  
    /**  
     * Set the value related to the column: proxyServerIp.
	 * @param proxyServerIp the proxyServerIp value you wish to set
	 */
	void setProxyServerIp(final String proxyServerIp);

    /**
     * Return the value associated with the column: siteOwnerId.
	 * @return A Long object (this.siteOwnerId)
	 */
	Long getSiteOwnerId();
	

  
    /**  
     * Set the value related to the column: siteOwnerId.
	 * @param siteOwnerId the siteOwnerId value you wish to set
	 */
	void setSiteOwnerId(final Long siteOwnerId);

	// end of interface
}