package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: Publisher.
 * @author autogenerated
 */

public interface IPublisher {



    /**
     * Return the value associated with the column: accountName.
	 * @return A String object (this.accountName)
	 */
	String getAccountName();
	

  
    /**  
     * Set the value related to the column: accountName.
	 * @param accountName the accountName value you wish to set
	 */
	void setAccountName(final String accountName);

    /**
     * Return the value associated with the column: accountPassword.
	 * @return A String object (this.accountPassword)
	 */
	String getAccountPassword();
	

  
    /**  
     * Set the value related to the column: accountPassword.
	 * @param accountPassword the accountPassword value you wish to set
	 */
	void setAccountPassword(final String accountPassword);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: publisherName.
	 * @return A String object (this.publisherName)
	 */
	String getPublisherName();
	

  
    /**  
     * Set the value related to the column: publisherName.
	 * @param publisherName the publisherName value you wish to set
	 */
	void setPublisherName(final String publisherName);

	// end of interface
}