package com.cm.rotator.domain.rotator.model.obj.rotator.iface;
import java.util.Date;


/** 
 * Object interface mapping for hibernate-handled table: RequestData.
 * @author autogenerated
 */

public interface IRequestdata {



    /**
     * Return the value associated with the column: countryCode.
	 * @return A String object (this.countryCode)
	 */
	String getCountryCode();
	

  
    /**  
     * Set the value related to the column: countryCode.
	 * @param countryCode the countryCode value you wish to set
	 */
	void setCountryCode(final String countryCode);

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	Date getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Date createdAt);

    /**
     * Return the value associated with the column: httpReferer.
	 * @return A String object (this.httpReferer)
	 */
	String getHttpReferer();
	

  
    /**  
     * Set the value related to the column: httpReferer.
	 * @param httpReferer the httpReferer value you wish to set
	 */
	void setHttpReferer(final String httpReferer);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: ip.
	 * @return A String object (this.ip)
	 */
	String getIp();
	

  
    /**  
     * Set the value related to the column: ip.
	 * @param ip the ip value you wish to set
	 */
	void setIp(final String ip);

    /**
     * Return the value associated with the column: pathTranslated.
	 * @return A String object (this.pathTranslated)
	 */
	String getPathTranslated();
	

  
    /**  
     * Set the value related to the column: pathTranslated.
	 * @param pathTranslated the pathTranslated value you wish to set
	 */
	void setPathTranslated(final String pathTranslated);

    /**
     * Return the value associated with the column: port.
	 * @return A Integer object (this.port)
	 */
	Integer getPort();
	

  
    /**  
     * Set the value related to the column: port.
	 * @param port the port value you wish to set
	 */
	void setPort(final Integer port);

    /**
     * Return the value associated with the column: requestMethod.
	 * @return A String object (this.requestMethod)
	 */
	String getRequestMethod();
	

  
    /**  
     * Set the value related to the column: requestMethod.
	 * @param requestMethod the requestMethod value you wish to set
	 */
	void setRequestMethod(final String requestMethod);

    /**
     * Return the value associated with the column: requestUri.
	 * @return A String object (this.requestUri)
	 */
	String getRequestUri();
	

  
    /**  
     * Set the value related to the column: requestUri.
	 * @param requestUri the requestUri value you wish to set
	 */
	void setRequestUri(final String requestUri);

    /**
     * Return the value associated with the column: userAgent.
	 * @return A String object (this.userAgent)
	 */
	String getUserAgent();
	

  
    /**  
     * Set the value related to the column: userAgent.
	 * @param userAgent the userAgent value you wish to set
	 */
	void setUserAgent(final String userAgent);

	// end of interface
}