package com.cm.rotator.domain.rotator.model.obj.rotator.iface;
import java.util.Date;


/** 
 * Object interface mapping for hibernate-handled table: RotatorRawTraffic.
 * @author autogenerated
 */

public interface IRotatorrawtraffic {



    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	Date getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Date createdAt);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: ip.
	 * @return A String object (this.ip)
	 */
	String getIp();
	

  
    /**  
     * Set the value related to the column: ip.
	 * @param ip the ip value you wish to set
	 */
	void setIp(final String ip);

    /**
     * Return the value associated with the column: pathPercent.
	 * @return A java.math.BigDecimal object (this.pathPercent)
	 */
	java.math.BigDecimal getPathPercent();
	

  
    /**  
     * Set the value related to the column: pathPercent.
	 * @param pathPercent the pathPercent value you wish to set
	 */
	void setPathPercent(final java.math.BigDecimal pathPercent);

    /**
     * Return the value associated with the column: requestDataId.
	 * @return A Long object (this.requestDataId)
	 */
	Long getRequestDataId();
	

  
    /**  
     * Set the value related to the column: requestDataId.
	 * @param requestDataId the requestDataId value you wish to set
	 */
	void setRequestDataId(final Long requestDataId);

    /**
     * Return the value associated with the column: rotatorDestinationPathId.
	 * @return A Long object (this.rotatorDestinationPathId)
	 */
	Long getRotatorDestinationPathId();
	

  
    /**  
     * Set the value related to the column: rotatorDestinationPathId.
	 * @param rotatorDestinationPathId the rotatorDestinationPathId value you wish to set
	 */
	void setRotatorDestinationPathId(final Long rotatorDestinationPathId);

    /**
     * Return the value associated with the column: url.
	 * @return A String object (this.url)
	 */
	String getUrl();
	

  
    /**  
     * Set the value related to the column: url.
	 * @param url the url value you wish to set
	 */
	void setUrl(final String url);

	// end of interface
}