package com.cm.rotator.domain.rotator.model.obj.rotator.iface;
import java.util.Date;


/** 
 * Object interface mapping for hibernate-handled table: Rotator.
 * @author autogenerated
 */

public interface IRotator {



    /**
     * Return the value associated with the column: active.
	 * @return A Boolean object (this.active)
	 */
	Boolean isActive();
	

  
    /**  
     * Set the value related to the column: active.
	 * @param active the active value you wish to set
	 */
	void setActive(final Boolean active);

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	Date getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Date createdAt);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: rotatorName.
	 * @return A String object (this.rotatorName)
	 */
	String getRotatorName();
	

  
    /**  
     * Set the value related to the column: rotatorName.
	 * @param rotatorName the rotatorName value you wish to set
	 */
	void setRotatorName(final String rotatorName);

    /**
     * Return the value associated with the column: updatedAt.
	 * @return A Date object (this.updatedAt)
	 */
	Date getUpdatedAt();
	

  
    /**  
     * Set the value related to the column: updatedAt.
	 * @param updatedAt the updatedAt value you wish to set
	 */
	void setUpdatedAt(final Date updatedAt);

	// end of interface
}