package com.cm.rotator.domain.rotator.model.obj.rotator.iface;
import java.util.Date;


/** 
 * Object interface mapping for hibernate-handled table: RotatorDestinationPath.
 * @author autogenerated
 */

public interface IRotatordestinationpath {



    /**
     * Return the value associated with the column: active.
	 * @return A Boolean object (this.active)
	 */
	Boolean isActive();
	

  
    /**  
     * Set the value related to the column: active.
	 * @param active the active value you wish to set
	 */
	void setActive(final Boolean active);

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	Date getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Date createdAt);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: pathName.
	 * @return A String object (this.pathName)
	 */
	String getPathName();
	

  
    /**  
     * Set the value related to the column: pathName.
	 * @param pathName the pathName value you wish to set
	 */
	void setPathName(final String pathName);

    /**
     * Return the value associated with the column: pathPercent.
	 * @return A java.math.BigDecimal object (this.pathPercent)
	 */
	java.math.BigDecimal getPathPercent();
	

  
    /**  
     * Set the value related to the column: pathPercent.
	 * @param pathPercent the pathPercent value you wish to set
	 */
	void setPathPercent(final java.math.BigDecimal pathPercent);

    /**
     * Return the value associated with the column: rotatorId.
	 * @return A Long object (this.rotatorId)
	 */
	Long getRotatorId();
	

  
    /**  
     * Set the value related to the column: rotatorId.
	 * @param rotatorId the rotatorId value you wish to set
	 */
	void setRotatorId(final Long rotatorId);

    /**
     * Return the value associated with the column: updatedAt.
	 * @return A Date object (this.updatedAt)
	 */
	Date getUpdatedAt();
	

  
    /**  
     * Set the value related to the column: updatedAt.
	 * @param updatedAt the updatedAt value you wish to set
	 */
	void setUpdatedAt(final Date updatedAt);

    /**
     * Return the value associated with the column: url.
	 * @return A String object (this.url)
	 */
	String getUrl();
	

  
    /**  
     * Set the value related to the column: url.
	 * @param url the url value you wish to set
	 */
	void setUrl(final String url);

	// end of interface
}