package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: SetCampaignMap.
 * @author autogenerated
 */

public interface ISetcampaignmap {



    /**
     * Return the value associated with the column: countryUrlCampaignId.
	 * @return A Long object (this.countryUrlCampaignId)
	 */
	Long getCountryUrlCampaignId();
	

  
    /**  
     * Set the value related to the column: countryUrlCampaignId.
	 * @param countryUrlCampaignId the countryUrlCampaignId value you wish to set
	 */
	void setCountryUrlCampaignId(final Long countryUrlCampaignId);

    /**
     * Return the value associated with the column: foreignSetId.
	 * @return A Long object (this.foreignSetId)
	 */
	Long getForeignSetId();
	

  
    /**  
     * Set the value related to the column: foreignSetId.
	 * @param foreignSetId the foreignSetId value you wish to set
	 */
	void setForeignSetId(final Long foreignSetId);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

	// end of interface
}