package com.cm.rotator.domain.rotator.model.obj.rotator.iface;
import java.util.Date;


/** 
 * Object interface mapping for hibernate-handled table: Tester.
 * @author autogenerated
 */

public interface ITester {



    /**
     * Return the value associated with the column: createdat.
	 * @return A Date object (this.createdat)
	 */
	Date getCreatedat();
	

  
    /**  
     * Set the value related to the column: createdat.
	 * @param createdat the createdat value you wish to set
	 */
	void setCreatedat(final Date createdat);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

	// end of interface
}