package com.cm.rotator.domain.rotator.model.obj.rotator.iface;


/** 
 * Object interface mapping for hibernate-handled table: TrafficOptimizerDefaults.
 * @author autogenerated
 */

public interface ITrafficoptimizerdefaults {



    /**
     * Return the value associated with the column: foreignSetId.
	 * @return A Long object (this.foreignSetId)
	 */
	Long getForeignSetId();
	

  
    /**  
     * Set the value related to the column: foreignSetId.
	 * @param foreignSetId the foreignSetId value you wish to set
	 */
	void setForeignSetId(final Long foreignSetId);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: publisherId.
	 * @return A Long object (this.publisherId)
	 */
	Long getPublisherId();
	

  
    /**  
     * Set the value related to the column: publisherId.
	 * @param publisherId the publisherId value you wish to set
	 */
	void setPublisherId(final Long publisherId);

    /**
     * Return the value associated with the column: rotatorId.
	 * @return A Long object (this.rotatorId)
	 */
	Long getRotatorId();
	

  
    /**  
     * Set the value related to the column: rotatorId.
	 * @param rotatorId the rotatorId value you wish to set
	 */
	void setRotatorId(final Long rotatorId);

	// end of interface
}