package com.cm.rotator.domain.rotator.model.obj.rotator.iface;
import java.util.Date;


/** 
 * Object interface mapping for hibernate-handled table: UnmatchedConversion.
 * @author autogenerated
 */

public interface IUnmatchedconversion {



    /**
     * Return the value associated with the column: advertiserId.
	 * @return A Long object (this.advertiserId)
	 */
	Long getAdvertiserId();
	

  
    /**  
     * Set the value related to the column: advertiserId.
	 * @param advertiserId the advertiserId value you wish to set
	 */
	void setAdvertiserId(final Long advertiserId);

    /**
     * Return the value associated with the column: countryUrlCampaignId.
	 * @return A Long object (this.countryUrlCampaignId)
	 */
	Long getCountryUrlCampaignId();
	

  
    /**  
     * Set the value related to the column: countryUrlCampaignId.
	 * @param countryUrlCampaignId the countryUrlCampaignId value you wish to set
	 */
	void setCountryUrlCampaignId(final Long countryUrlCampaignId);

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	Date getCreatedAt();
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	void setCreatedAt(final Date createdAt);

    /**
     * Return the value associated with the column: cAdvertiserId.
	 * @return A Long object (this.cAdvertiserId)
	 */
	Long getCAdvertiserId();
	

  
    /**  
     * Set the value related to the column: cAdvertiserId.
	 * @param cAdvertiserId the cAdvertiserId value you wish to set
	 */
	void setCAdvertiserId(final Long cAdvertiserId);

    /**
     * Return the value associated with the column: cCountryUrlCampaignId.
	 * @return A Long object (this.cCountryUrlCampaignId)
	 */
	Long getCCountryUrlCampaignId();
	

  
    /**  
     * Set the value related to the column: cCountryUrlCampaignId.
	 * @param cCountryUrlCampaignId the cCountryUrlCampaignId value you wish to set
	 */
	void setCCountryUrlCampaignId(final Long cCountryUrlCampaignId);

    /**
     * Return the value associated with the column: cHash.
	 * @return A String object (this.cHash)
	 */
	String getCHash();
	

  
    /**  
     * Set the value related to the column: cHash.
	 * @param cHash the cHash value you wish to set
	 */
	void setCHash(final String cHash);

    /**
     * Return the value associated with the column: cRawTrafficId.
	 * @return A Long object (this.cRawTrafficId)
	 */
	Long getCRawTrafficId();
	

  
    /**  
     * Set the value related to the column: cRawTrafficId.
	 * @param cRawTrafficId the cRawTrafficId value you wish to set
	 */
	void setCRawTrafficId(final Long cRawTrafficId);

    /**
     * Return the value associated with the column: httpReferer.
	 * @return A String object (this.httpReferer)
	 */
	String getHttpReferer();
	

  
    /**  
     * Set the value related to the column: httpReferer.
	 * @param httpReferer the httpReferer value you wish to set
	 */
	void setHttpReferer(final String httpReferer);

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	Long getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Long id);

    /**
     * Return the value associated with the column: ip.
	 * @return A String object (this.ip)
	 */
	String getIp();
	

  
    /**  
     * Set the value related to the column: ip.
	 * @param ip the ip value you wish to set
	 */
	void setIp(final String ip);

    /**
     * Return the value associated with the column: message.
	 * @return A String object (this.message)
	 */
	String getMessage();
	

  
    /**  
     * Set the value related to the column: message.
	 * @param message the message value you wish to set
	 */
	void setMessage(final String message);

    /**
     * Return the value associated with the column: rawTrafficId.
	 * @return A Long object (this.rawTrafficId)
	 */
	Long getRawTrafficId();
	

  
    /**  
     * Set the value related to the column: rawTrafficId.
	 * @param rawTrafficId the rawTrafficId value you wish to set
	 */
	void setRawTrafficId(final Long rawTrafficId);

    /**
     * Return the value associated with the column: uri.
	 * @return A String object (this.uri)
	 */
	String getUri();
	

  
    /**  
     * Set the value related to the column: uri.
	 * @param uri the uri value you wish to set
	 */
	void setUri(final String uri);

	// end of interface
}