package com.cn.rotator.domain.dao;

 
/**
 * DAO interface for table: Campaignreportingtype.
 * @author autogenerated
 */
public interface CampaignreportingtypeDao {
	// constructor only
}

