package com.cn.rotator.domain.dao;

import com.cn.rotator.domain.dom.Rotator;

/**
 * DAO interface for table: Rotator.
 * @author autogenerated
 */
public interface RotatorDao  {

    public Rotator findRotatorById(long id);
}

