package com.cn.rotator.domain.dao;


/**
 * DAO interface for table: Rotatordestinationpath.
 * @author autogenerated
 */
public interface RotatordestinationpathDao  {
	// constructor only
}

