package com.cn.rotator.domain.dao;


/**
 * DAO interface for table: Rotatorconvertedtraffic.
 * @author autogenerated
 */
public interface RotatorconvertedtrafficDao  {
	// constructor only
}

