package com.cn.rotator.domain.dao;


import com.cn.rotator.domain.dom.RotatorDestinationPath;

/**
 * DAO interface for table: Rotatordestinationpath.
 * @author autogenerated
 */
public interface RotatorDestinationPathDao  {

    public RotatorDestinationPath findRotatorDestinationPathByRotatorId(long id);
}

