package com.cn.rotator.domain.dao;


/**
 * DAO interface for table: Trafficoptimizerdefaults.
 * @author autogenerated
 */
public interface TrafficoptimizerdefaultsDao  {
	// constructor only
}

