package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Campaigntype;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.CampaigntypeDao;
 
 
/**
 * DAO for table: Campaigntype.
 * @author autogenerated
 */
@Repository
public class CampaigntypeDaoImpl extends GenericHibernateDaoImpl<Campaigntype, Long> implements CampaigntypeDao {
	
	/** Constructor method. */
		public CampaigntypeDaoImpl() {
			super(Campaigntype.class);
		}
	}

