package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Campaignreportingtype;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.CampaignreportingtypeDao;
 
 
/**
 * DAO for table: Campaignreportingtype.
 * @author autogenerated
 */
@Repository
public class CampaignreportingtypeDaoImpl extends GenericHibernateDaoImpl<Campaignreportingtype, Integer> implements CampaignreportingtypeDao {
	
	/** Constructor method. */
		public CampaignreportingtypeDaoImpl() {
			super(Campaignreportingtype.class);
		}
	}

