package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Countryurlcampaign;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.CountryurlcampaignDao;
 
 
/**
 * DAO for table: Countryurlcampaign.
 * @author autogenerated
 */
@Repository
public class CountryurlcampaignDaoImpl extends GenericHibernateDaoImpl<Countryurlcampaign, Long> implements CountryurlcampaignDao {
	
	/** Constructor method. */
		public CountryurlcampaignDaoImpl() {
			super(Countryurlcampaign.class);
		}
	}

