package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Foreignset;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.ForeignsetDao;
 
 
/**
 * DAO for table: Foreignset.
 * @author autogenerated
 */
@Repository
public class ForeignsetDaoImpl extends GenericHibernateDaoImpl<Foreignset, Long> implements ForeignsetDao {
	
	/** Constructor method. */
		public ForeignsetDaoImpl() {
			super(Foreignset.class);
		}
	}

