package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Proxyserver;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.ProxyserverDao;
 
 
/**
 * DAO for table: Proxyserver.
 * @author autogenerated
 */
@Repository
public class ProxyserverDaoImpl extends GenericHibernateDaoImpl<Proxyserver, Long> implements ProxyserverDao {
	
	/** Constructor method. */
		public ProxyserverDaoImpl() {
			super(Proxyserver.class);
		}
	}

