package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Publishersetmap;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.PublishersetmapDao;
 
 
/**
 * DAO for table: Publishersetmap.
 * @author autogenerated
 */
@Repository
public class PublishersetmapDaoImpl extends GenericHibernateDaoImpl<Publishersetmap, Integer> implements PublishersetmapDao {
	
	/** Constructor method. */
		public PublishersetmapDaoImpl() {
			super(Publishersetmap.class);
		}
	}

