package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Publisher;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.PublisherDao;
 
 
/**
 * DAO for table: Publisher.
 * @author autogenerated
 */
@Repository
public class PublisherDaoImpl extends GenericHibernateDaoImpl<Publisher, Long> implements PublisherDao {
	
	/** Constructor method. */
		public PublisherDaoImpl() {
			super(Publisher.class);
		}
	}

