package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rawtraffic;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.RawtrafficDao;
 
 
/**
 * DAO for table: Rawtraffic.
 * @author autogenerated
 */
@Repository
public class RawtrafficDaoImpl extends GenericHibernateDaoImpl<Rawtraffic, Long> implements RawtrafficDao {
	
	/** Constructor method. */
		public RawtrafficDaoImpl() {
			super(Rawtraffic.class);
		}
	}

