package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Requestdata;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.RequestdataDao;
 
 
/**
 * DAO for table: Requestdata.
 * @author autogenerated
 */
@Repository
public class RequestdataDaoImpl extends GenericHibernateDaoImpl<Requestdata, Long> implements RequestdataDao {
	
	/** Constructor method. */
		public RequestdataDaoImpl() {
			super(Requestdata.class);
		}
	}

