package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rotatorrawtraffic;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.RotatorrawtrafficDao;
 
 
/**
 * DAO for table: Rotatorrawtraffic.
 * @author autogenerated
 */
@Repository
public class RotatorrawtrafficDaoImpl extends GenericHibernateDaoImpl<Rotatorrawtraffic, Integer> implements RotatorrawtrafficDao {
	
	/** Constructor method. */
		public RotatorrawtrafficDaoImpl() {
			super(Rotatorrawtraffic.class);
		}
	}

