package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rotator;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.RotatorDao;
 
 
/**
 * DAO for table: Rotator.
 * @author autogenerated
 */
@Repository
public class RotatorDaoImpl extends GenericHibernateDaoImpl<Rotator, Integer> implements RotatorDao {
	
	/** Constructor method. */
		public RotatorDaoImpl() {
			super(Rotator.class);
		}
	}

