package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rotatorconvertedtraffic;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.RotatorconvertedtrafficDao;
 
 
/**
 * DAO for table: Rotatorconvertedtraffic.
 * @author autogenerated
 */
@Repository
public class RotatorconvertedtrafficDaoImpl extends GenericHibernateDaoImpl<Rotatorconvertedtraffic, Integer> implements RotatorconvertedtrafficDao {
	
	/** Constructor method. */
		public RotatorconvertedtrafficDaoImpl() {
			super(Rotatorconvertedtraffic.class);
		}
	}

