package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Setcampaignmap;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.SetcampaignmapDao;
 
 
/**
 * DAO for table: Setcampaignmap.
 * @author autogenerated
 */
@Repository
public class SetcampaignmapDaoImpl extends GenericHibernateDaoImpl<Setcampaignmap, Long> implements SetcampaignmapDao {
	
	/** Constructor method. */
		public SetcampaignmapDaoImpl() {
			super(Setcampaignmap.class);
		}
	}

