package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Tester;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.TesterDao;
 
 
/**
 * DAO for table: Tester.
 * @author autogenerated
 */
@Repository
public class TesterDaoImpl extends GenericHibernateDaoImpl<Tester, Long> implements TesterDao {
	
	/** Constructor method. */
		public TesterDaoImpl() {
			super(Tester.class);
		}
	}

