package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Trafficoptimizerdefaults;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.TrafficoptimizerdefaultsDao;
 
 
/**
 * DAO for table: Trafficoptimizerdefaults.
 * @author autogenerated
 */
@Repository
public class TrafficoptimizerdefaultsDaoImpl extends GenericHibernateDaoImpl<Trafficoptimizerdefaults, Integer> implements TrafficoptimizerdefaultsDao {
	
	/** Constructor method. */
		public TrafficoptimizerdefaultsDaoImpl() {
			super(Trafficoptimizerdefaults.class);
		}
	}

