package com.cm.rotator.domain.rotator.model.dao.rotator.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.cm.rotator.domain.rotator.model.obj.rotator.Unmatchedconversion;
import org.springframework.stereotype.Repository;
import com.cm.rotator.domain.rotator.model.dao.rotator.UnmatchedconversionDao;
 
 
/**
 * DAO for table: Unmatchedconversion.
 * @author autogenerated
 */
@Repository
public class UnmatchedconversionDaoImpl extends GenericHibernateDaoImpl<Unmatchedconversion, Long> implements UnmatchedconversionDao {
	
	/** Constructor method. */
		public UnmatchedconversionDaoImpl() {
			super(Unmatchedconversion.class);
		}
	}

