package com.cn.rotator.domain.dom;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Object mapping for hibernate-handled table: Rotator.
 * 
 * @author autogenerated
 */
@Entity
@Table(name = "Rotator", catalog = "rotator")
public class Rotator implements Serializable {

    private static final long serialVersionUID = -559008639L;

    @Id
    private long id;

    private String rotatorName;

    @Temporal(TemporalType.DATE)
    private Date createdAt;

    @Temporal(TemporalType.DATE)
    private Date updatedAt;

    private boolean active;

    @OneToMany
    private ArrayList<RotatorDestinationPath> rotatorDestinationPaths;

    public Rotator() {}

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public ArrayList<RotatorDestinationPath> getRotatorDestinationPaths() {
        return rotatorDestinationPaths;
    }

    public void setRotatorDestinationPaths(ArrayList<RotatorDestinationPath> rotatorDestinationPaths) {
        this.rotatorDestinationPaths = rotatorDestinationPaths;
    }

    public String getRotatorName() {
        return rotatorName;
    }

    public void setRotatorName(String rotatorName) {
        this.rotatorName = rotatorName;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }


}
