package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Advertiser;
 
/**
 * DAO interface for table: Advertiser.
 * @author autogenerated
 */
public interface AdvertiserDao extends GenericDAO<Advertiser,  Long>  {
	// constructor only
}

