package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Campaignreportingtype;
 
/**
 * DAO interface for table: Campaignreportingtype.
 * @author autogenerated
 */
public interface CampaignreportingtypeDao extends GenericDAO<Campaignreportingtype,  Integer>  {
	// constructor only
}

