package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Campaigntype;
 
/**
 * DAO interface for table: Campaigntype.
 * @author autogenerated
 */
public interface CampaigntypeDao extends GenericDAO<Campaigntype,  Long>  {
	// constructor only
}

