package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Convertedtraffic;
 
/**
 * DAO interface for table: Convertedtraffic.
 * @author autogenerated
 */
public interface ConvertedtrafficDao extends GenericDAO<Convertedtraffic,  Long>  {
	// constructor only
}

