package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Countryurlcampaign;
 
/**
 * DAO interface for table: Countryurlcampaign.
 * @author autogenerated
 */
public interface CountryurlcampaignDao extends GenericDAO<Countryurlcampaign,  Long>  {
	// constructor only
}

