package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Foreignset;
 
/**
 * DAO interface for table: Foreignset.
 * @author autogenerated
 */
public interface ForeignsetDao extends GenericDAO<Foreignset,  Long>  {
	// constructor only
}

