package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Proxyserver;
 
/**
 * DAO interface for table: Proxyserver.
 * @author autogenerated
 */
public interface ProxyserverDao extends GenericDAO<Proxyserver,  Long>  {
	// constructor only
}

