package com.cm.rotator.domain.rotator.model.obj.rotator;

import com.cm.rotator.domain.rotator.model.obj.rotator.iface.IProxyserver;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: ProxyServer.
 * @author autogenerated
 */

@Entity
@Table(name = "ProxyServer", catalog = "rotator")
public class Proxyserver implements Cloneable, Serializable, IPojoGenEntity, IProxyserver {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559008644L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Long> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
	
	/** hashCode temporary storage. */
	private volatile Long hashCode;
	

	/** Field mapping. */
	private Long id = 0L; // init for hibernate bug workaround
	/** Field mapping. */
	private String proxyServerIp;
	/** Field mapping. */
	private Long siteOwnerId;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Proxyserver() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Proxyserver(Long id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param id Long object;
	 * @param proxyServerIp String object;
	 * @param siteOwnerId Long object;
	 */
	public Proxyserver(Long id, String proxyServerIp, Long siteOwnerId) {

		this.id = id;
		this.proxyServerIp = proxyServerIp;
		this.siteOwnerId = siteOwnerId;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Proxyserver.class;
	}
 

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column( name = "id", nullable = false  )
	public Long getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Long id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0L) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: proxyServerIp.
	 * @return A String object (this.proxyServerIp)
	 */
	@Column( name = "proxy_server_ip", nullable = false, length = 16  )
	public String getProxyServerIp() {
		return this.proxyServerIp;
		
	}
	

  
    /**  
     * Set the value related to the column: proxyServerIp.
	 * @param proxyServerIp the proxyServerIp value you wish to set
	 */
	public void setProxyServerIp(final String proxyServerIp) {
		this.proxyServerIp = proxyServerIp;
	}

    /**
     * Return the value associated with the column: siteOwnerId.
	 * @return A Long object (this.siteOwnerId)
	 */
	@Column( name = "site_owner_id", nullable = false  )
	public Long getSiteOwnerId() {
		return this.siteOwnerId;
		
	}
	

  
    /**  
     * Set the value related to the column: siteOwnerId.
	 * @param siteOwnerId the siteOwnerId value you wish to set
	 */
	public void setSiteOwnerId(final Long siteOwnerId) {
		this.siteOwnerId = siteOwnerId;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Proxyserver clone() throws CloneNotSupportedException {
		
        final Proxyserver copy = (Proxyserver)super.clone();

		copy.setId(this.getId());
		copy.setProxyServerIp(this.getProxyServerIp());
		copy.setSiteOwnerId(this.getSiteOwnerId());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("id: " + this.getId() + ", ");
		sb.append("proxyServerIp: " + this.getProxyServerIp() + ", ");
		sb.append("siteOwnerId: " + this.getSiteOwnerId());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Proxyserver that; 
		try {
			that = (Proxyserver) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getProxyServerIp() == null) && (that.getProxyServerIp() == null)) || (getProxyServerIp() != null && getProxyServerIp().equals(that.getProxyServerIp())));
		result = result && (((getSiteOwnerId() == null) && (that.getSiteOwnerId() == null)) || (getSiteOwnerId() != null && getSiteOwnerId().equals(that.getSiteOwnerId())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Long newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0L) {
							newHashCode = getId();
						} else {
							newHashCode = (long) super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
		return (int) (this.hashCode & 0xffffff);
	}
	

	
}
