package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Publishersetmap;
 
/**
 * DAO interface for table: Publishersetmap.
 * @author autogenerated
 */
public interface PublishersetmapDao extends GenericDAO<Publishersetmap,  Integer>  {
	// constructor only
}

