package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Publisher;
 
/**
 * DAO interface for table: Publisher.
 * @author autogenerated
 */
public interface PublisherDao extends GenericDAO<Publisher,  Long>  {
	// constructor only
}

