package com.cm.rotator.domain.rotator.model.obj.rotator;

import com.cm.rotator.domain.rotator.model.obj.rotator.iface.IPublishersetmap;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: PublisherSetMap.
 * @author autogenerated
 */

@Entity
@Table(name = "PublisherSetMap", catalog = "rotator")
public class Publishersetmap implements Cloneable, Serializable, IPojoGenEntity, IPublishersetmap {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559008642L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Integer> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Integer>());
	
	/** hashCode temporary storage. */
	private volatile Integer hashCode;
	

	/** Field mapping. */
	private Long foreignSetId;
	/** Field mapping. */
	private Integer id = 0; // init for hibernate bug workaround
	/** Field mapping. */
	private Long publisherId;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Publishersetmap() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Publishersetmap(Integer id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param foreignSetId Long object;
	 * @param id Integer object;
	 * @param publisherId Long object;
	 */
	public Publishersetmap(Long foreignSetId, Integer id, Long publisherId) {

		this.foreignSetId = foreignSetId;
		this.id = id;
		this.publisherId = publisherId;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Publishersetmap.class;
	}
 

    /**
     * Return the value associated with the column: foreignSetId.
	 * @return A Long object (this.foreignSetId)
	 */
	@Column( name = "foreign_set_id", nullable = false  )
	public Long getForeignSetId() {
		return this.foreignSetId;
		
	}
	

  
    /**  
     * Set the value related to the column: foreignSetId.
	 * @param foreignSetId the foreignSetId value you wish to set
	 */
	public void setForeignSetId(final Long foreignSetId) {
		this.foreignSetId = foreignSetId;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column( name = "id", nullable = false  )
	public Integer getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Integer id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: publisherId.
	 * @return A Long object (this.publisherId)
	 */
	@Column( name = "publisher_id", nullable = false  )
	public Long getPublisherId() {
		return this.publisherId;
		
	}
	

  
    /**  
     * Set the value related to the column: publisherId.
	 * @param publisherId the publisherId value you wish to set
	 */
	public void setPublisherId(final Long publisherId) {
		this.publisherId = publisherId;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Publishersetmap clone() throws CloneNotSupportedException {
		
        final Publishersetmap copy = (Publishersetmap)super.clone();

		copy.setForeignSetId(this.getForeignSetId());
		copy.setId(this.getId());
		copy.setPublisherId(this.getPublisherId());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("foreignSetId: " + this.getForeignSetId() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("publisherId: " + this.getPublisherId());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Publishersetmap that; 
		try {
			that = (Publishersetmap) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getForeignSetId() == null) && (that.getForeignSetId() == null)) || (getForeignSetId() != null && getForeignSetId().equals(that.getForeignSetId())));
		result = result && (((getPublisherId() == null) && (that.getPublisherId() == null)) || (getPublisherId() != null && getPublisherId().equals(that.getPublisherId())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Integer newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0) {
							newHashCode = getId();
						} else {
							newHashCode = super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode;
	}
	

	
}
