package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rawtraffic;
 
/**
 * DAO interface for table: Rawtraffic.
 * @author autogenerated
 */
public interface RawtrafficDao extends GenericDAO<Rawtraffic,  Long>  {
	// constructor only
}

