package com.cm.rotator.domain.rotator.model.obj.rotator;

import com.cm.rotator.domain.rotator.model.obj.rotator.iface.IRawtraffic;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: RawTraffic.
 * @author autogenerated
 */

@Entity
@Table(name = "RawTraffic", catalog = "rotator")
public class Rawtraffic implements Cloneable, Serializable, IPojoGenEntity, IRawtraffic {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559008641L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Long> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
	
	/** hashCode temporary storage. */
	private volatile Long hashCode;
	

	/** Field mapping. */
	private String countryCode;
	/** Field mapping. */
	private Long countryUrlCampaignId;
	/** Field mapping. */
	private Date createdAt;
	/** Field mapping. */
	private Long id = 0L; // init for hibernate bug workaround
	/** Field mapping. */
	private String ip;
	/** Field mapping. */
	private Long publisherId;
	/** Field mapping. */
	private String publisherUid;
	/** Field mapping. */
	private Long requestDataId;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Rawtraffic() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Rawtraffic(Long id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param countryCode String object;
	 * @param countryUrlCampaignId Long object;
	 * @param createdAt Date object;
	 * @param id Long object;
	 * @param publisherId Long object;
	 * @param publisherUid String object;
	 */
	public Rawtraffic(String countryCode, Long countryUrlCampaignId, Date createdAt, 					
			Long id, Long publisherId, String publisherUid) {

		this.countryCode = countryCode;
		this.countryUrlCampaignId = countryUrlCampaignId;
		this.createdAt = createdAt;
		this.id = id;
		this.publisherId = publisherId;
		this.publisherUid = publisherUid;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Rawtraffic.class;
	}
 

    /**
     * Return the value associated with the column: countryCode.
	 * @return A String object (this.countryCode)
	 */
	@Column( name = "country_code", nullable = false, length = 2  )
	public String getCountryCode() {
		return this.countryCode;
		
	}
	

  
    /**  
     * Set the value related to the column: countryCode.
	 * @param countryCode the countryCode value you wish to set
	 */
	public void setCountryCode(final String countryCode) {
		this.countryCode = countryCode;
	}

    /**
     * Return the value associated with the column: countryUrlCampaignId.
	 * @return A Long object (this.countryUrlCampaignId)
	 */
	@Column( name = "country_url_campaign_id", nullable = false  )
	public Long getCountryUrlCampaignId() {
		return this.countryUrlCampaignId;
		
	}
	

  
    /**  
     * Set the value related to the column: countryUrlCampaignId.
	 * @param countryUrlCampaignId the countryUrlCampaignId value you wish to set
	 */
	public void setCountryUrlCampaignId(final Long countryUrlCampaignId) {
		this.countryUrlCampaignId = countryUrlCampaignId;
	}

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	@Column( name = "created_at", nullable = false  )
	public Date getCreatedAt() {
		return this.createdAt;
		
	}
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	public void setCreatedAt(final Date createdAt) {
		this.createdAt = createdAt;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column( name = "id", nullable = false  )
	public Long getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Long id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0L) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: ip.
	 * @return A String object (this.ip)
	 */
	@Column( length = 15  )
	public String getIp() {
		return this.ip;
		
	}
	

  
    /**  
     * Set the value related to the column: ip.
	 * @param ip the ip value you wish to set
	 */
	public void setIp(final String ip) {
		this.ip = ip;
	}

    /**
     * Return the value associated with the column: publisherId.
	 * @return A Long object (this.publisherId)
	 */
	@Column( name = "publisher_id", nullable = false  )
	public Long getPublisherId() {
		return this.publisherId;
		
	}
	

  
    /**  
     * Set the value related to the column: publisherId.
	 * @param publisherId the publisherId value you wish to set
	 */
	public void setPublisherId(final Long publisherId) {
		this.publisherId = publisherId;
	}

    /**
     * Return the value associated with the column: publisherUid.
	 * @return A String object (this.publisherUid)
	 */
	@Column( name = "publisher_uid", nullable = false, length = 15  )
	public String getPublisherUid() {
		return this.publisherUid;
		
	}
	

  
    /**  
     * Set the value related to the column: publisherUid.
	 * @param publisherUid the publisherUid value you wish to set
	 */
	public void setPublisherUid(final String publisherUid) {
		this.publisherUid = publisherUid;
	}

    /**
     * Return the value associated with the column: requestDataId.
	 * @return A Long object (this.requestDataId)
	 */
	@Column( name = "request_data_id"  )
	public Long getRequestDataId() {
		return this.requestDataId;
		
	}
	

  
    /**  
     * Set the value related to the column: requestDataId.
	 * @param requestDataId the requestDataId value you wish to set
	 */
	public void setRequestDataId(final Long requestDataId) {
		this.requestDataId = requestDataId;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Rawtraffic clone() throws CloneNotSupportedException {
		
        final Rawtraffic copy = (Rawtraffic)super.clone();

		copy.setCountryCode(this.getCountryCode());
		copy.setCountryUrlCampaignId(this.getCountryUrlCampaignId());
		copy.setCreatedAt(this.getCreatedAt());
		copy.setId(this.getId());
		copy.setIp(this.getIp());
		copy.setPublisherId(this.getPublisherId());
		copy.setPublisherUid(this.getPublisherUid());
		copy.setRequestDataId(this.getRequestDataId());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("countryCode: " + this.getCountryCode() + ", ");
		sb.append("countryUrlCampaignId: " + this.getCountryUrlCampaignId() + ", ");
		sb.append("createdAt: " + this.getCreatedAt() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("ip: " + this.getIp() + ", ");
		sb.append("publisherId: " + this.getPublisherId() + ", ");
		sb.append("publisherUid: " + this.getPublisherUid() + ", ");
		sb.append("requestDataId: " + this.getRequestDataId());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Rawtraffic that; 
		try {
			that = (Rawtraffic) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getCountryCode() == null) && (that.getCountryCode() == null)) || (getCountryCode() != null && getCountryCode().equals(that.getCountryCode())));
		result = result && (((getCountryUrlCampaignId() == null) && (that.getCountryUrlCampaignId() == null)) || (getCountryUrlCampaignId() != null && getCountryUrlCampaignId().equals(that.getCountryUrlCampaignId())));
		result = result && (((getCreatedAt() == null) && (that.getCreatedAt() == null)) || (getCreatedAt() != null && getCreatedAt().equals(that.getCreatedAt())));
		result = result && (((getIp() == null) && (that.getIp() == null)) || (getIp() != null && getIp().equals(that.getIp())));
		result = result && (((getPublisherId() == null) && (that.getPublisherId() == null)) || (getPublisherId() != null && getPublisherId().equals(that.getPublisherId())));
		result = result && (((getPublisherUid() == null) && (that.getPublisherUid() == null)) || (getPublisherUid() != null && getPublisherUid().equals(that.getPublisherUid())));
		result = result && (((getRequestDataId() == null) && (that.getRequestDataId() == null)) || (getRequestDataId() != null && getRequestDataId().equals(that.getRequestDataId())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Long newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0L) {
							newHashCode = getId();
						} else {
							newHashCode = (long) super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
		return (int) (this.hashCode & 0xffffff);
	}
	

	
}
