package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Requestdata;
 
/**
 * DAO interface for table: Requestdata.
 * @author autogenerated
 */
public interface RequestdataDao extends GenericDAO<Requestdata,  Long>  {
	// constructor only
}

