package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rotatorconvertedtraffic;
 
/**
 * DAO interface for table: Rotatorconvertedtraffic.
 * @author autogenerated
 */
public interface RotatorconvertedtrafficDao extends GenericDAO<Rotatorconvertedtraffic,  Integer>  {
	// constructor only
}

