package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rotatorrawtraffic;
 
/**
 * DAO interface for table: Rotatorrawtraffic.
 * @author autogenerated
 */
public interface RotatorrawtrafficDao extends GenericDAO<Rotatorrawtraffic,  Integer>  {
	// constructor only
}

