package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rotatordestinationpath;
 
/**
 * DAO interface for table: Rotatordestinationpath.
 * @author autogenerated
 */
public interface RotatordestinationpathDao extends GenericDAO<Rotatordestinationpath,  Integer>  {
	// constructor only
}

