package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Rotator;
 
/**
 * DAO interface for table: Rotator.
 * @author autogenerated
 */
public interface RotatorDao extends GenericDAO<Rotator,  Integer>  {
	// constructor only
}

