package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Setcampaignmap;
 
/**
 * DAO interface for table: Setcampaignmap.
 * @author autogenerated
 */
public interface SetcampaignmapDao extends GenericDAO<Setcampaignmap,  Long>  {
	// constructor only
}

