package com.cm.rotator.domain.rotator.model.obj.rotator;

import com.cm.rotator.domain.rotator.model.obj.rotator.iface.ISetcampaignmap;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: SetCampaignMap.
 * @author autogenerated
 */

@Entity
@Table(name = "SetCampaignMap", catalog = "rotator")
public class Setcampaignmap implements Cloneable, Serializable, IPojoGenEntity, ISetcampaignmap {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559008635L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Long> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
	
	/** hashCode temporary storage. */
	private volatile Long hashCode;
	

	/** Field mapping. */
	private Long countryUrlCampaignId;
	/** Field mapping. */
	private Long foreignSetId;
	/** Field mapping. */
	private Long id = 0L; // init for hibernate bug workaround
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Setcampaignmap() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Setcampaignmap(Long id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param countryUrlCampaignId Long object;
	 * @param foreignSetId Long object;
	 * @param id Long object;
	 */
	public Setcampaignmap(Long countryUrlCampaignId, Long foreignSetId, Long id) {

		this.countryUrlCampaignId = countryUrlCampaignId;
		this.foreignSetId = foreignSetId;
		this.id = id;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Setcampaignmap.class;
	}
 

    /**
     * Return the value associated with the column: countryUrlCampaignId.
	 * @return A Long object (this.countryUrlCampaignId)
	 */
	@Column( name = "country_url_campaign_id", nullable = false  )
	public Long getCountryUrlCampaignId() {
		return this.countryUrlCampaignId;
		
	}
	

  
    /**  
     * Set the value related to the column: countryUrlCampaignId.
	 * @param countryUrlCampaignId the countryUrlCampaignId value you wish to set
	 */
	public void setCountryUrlCampaignId(final Long countryUrlCampaignId) {
		this.countryUrlCampaignId = countryUrlCampaignId;
	}

    /**
     * Return the value associated with the column: foreignSetId.
	 * @return A Long object (this.foreignSetId)
	 */
	@Column( name = "foreign_set_id", nullable = false  )
	public Long getForeignSetId() {
		return this.foreignSetId;
		
	}
	

  
    /**  
     * Set the value related to the column: foreignSetId.
	 * @param foreignSetId the foreignSetId value you wish to set
	 */
	public void setForeignSetId(final Long foreignSetId) {
		this.foreignSetId = foreignSetId;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column( name = "id", nullable = false  )
	public Long getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Long id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0L) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Setcampaignmap clone() throws CloneNotSupportedException {
		
        final Setcampaignmap copy = (Setcampaignmap)super.clone();

		copy.setCountryUrlCampaignId(this.getCountryUrlCampaignId());
		copy.setForeignSetId(this.getForeignSetId());
		copy.setId(this.getId());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("countryUrlCampaignId: " + this.getCountryUrlCampaignId() + ", ");
		sb.append("foreignSetId: " + this.getForeignSetId() + ", ");
		sb.append("id: " + this.getId());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Setcampaignmap that; 
		try {
			that = (Setcampaignmap) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getCountryUrlCampaignId() == null) && (that.getCountryUrlCampaignId() == null)) || (getCountryUrlCampaignId() != null && getCountryUrlCampaignId().equals(that.getCountryUrlCampaignId())));
		result = result && (((getForeignSetId() == null) && (that.getForeignSetId() == null)) || (getForeignSetId() != null && getForeignSetId().equals(that.getForeignSetId())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Long newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0L) {
							newHashCode = getId();
						} else {
							newHashCode = (long) super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
		return (int) (this.hashCode & 0xffffff);
	}
	

	
}
