package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Trafficoptimizerdefaults;
 
/**
 * DAO interface for table: Trafficoptimizerdefaults.
 * @author autogenerated
 */
public interface TrafficoptimizerdefaultsDao extends GenericDAO<Trafficoptimizerdefaults,  Integer>  {
	// constructor only
}

