package com.cm.rotator.domain.rotator.model.dao.rotator;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.cm.rotator.domain.rotator.model.obj.rotator.Unmatchedconversion;
 
/**
 * DAO interface for table: Unmatchedconversion.
 * @author autogenerated
 */
public interface UnmatchedconversionDao extends GenericDAO<Unmatchedconversion,  Long>  {
	// constructor only
}

